## Modify elements & properties of arrays
- Append, insert, delete operations
- Scalar and vector operations
- Sorting operations

Operations to modify numpy arrays or the elements within

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0,6)
print(an_array)

[0 1 2 3 4 5]


### Modify a single element

In [5]:
# Fetches the element in index 0 and then changes it to 10
# The change will persist
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [7]:
# Reset the array 
an_array = np.arange(0,6)

### Append to an array

Append takes the array that you want to modify, and the elements that you want to append. <br>
If you want to append multiple elements, utilize the [] in python 

In [9]:
print(np.append(an_array, [6,7]))

[0 1 2 3 4 5 6 7]


### Inserting into an array

Insert takes the array that you want to modify, the index you want to insert into and the elements that you want to append

In [14]:
print(np.insert(an_array, 0, [10, 11]))

[10 11  0  1  2  3  4  5]


In [11]:
print(np.insert(an_array, 1, [10, 11]))

[ 0 10 11  1  2  3  4  5]


The index needs to exist in the array to work

### Deleting from an array

In [13]:
print(np.delete(an_array, 3))

[0 1 2 4 5]


Delete takes the array that you want to modify and the index that you want to remove. During the deletion, it'll shift everything over so there are no empty spaces.

## Scalar and Vector Operations

In [15]:
print(an_array * 2)

[ 0  2  4  6  8 10]


Scalar Operations take every element and applies the operation to the element

In [16]:
print(an_array + 2)

[2 3 4 5 6 7]


## Sorting Elements in an Array

Default sorting is to be sorted in ascending order. It is done in the most efficient way possible.

In [17]:
another_array = np.array([3, 6, 21, 9, 10, 11])

print(np.sort(another_array))

[ 3  6  9 10 11 21]


### Sorting in Descending Order

In [18]:
another_array = np.array([3, 6, 21, 9, 10, 11])

print(-np.sort(-another_array))

[21 11 10  9  6  3]


In [19]:
# Turns everything negative and then sorts it in that order
print(np.sort(-another_array))

[-21 -11 -10  -9  -6  -3]


In [20]:
# The negative in front of np.sort removes all the negatives from the elements in the array
print(-np.sort(-another_array))

[21 11 10  9  6  3]
