## Operations to fetch elements or properties
- Get elements based on index
- Get slices
- Get size and shape
- Get max, min and average

Functions to get elements or properties of matrices.

In [1]:
import numpy as np

In [4]:
a_matrix = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Getting elements based on index

In [5]:
print(a_matrix[0])
# Returns an array of an array still so its a matrix of 1 x 3

[[1 2 3]]


In [6]:
# Second array, index 0 
print(a_matrix[1,0])

4


## Getting slices 

In [9]:
# Return a slice of a row, a 1 x 2 matrix
print(a_matrix[2, (1,2)])

[[8 9]]


In [10]:
# Return a slice of a row, a 1 x 2 matrix
print(a_matrix[2, 1:3])

[[8 9]]


## Getting size and shape

In [11]:
print(a_matrix.size)

9


In [12]:
print(a_matrix.shape)
# Returns a tuple of the matrix size

(3, 3)


## Get max, min and average

In [16]:
# Option 1
print(np.amax(a_matrix))
print(np.amin(a_matrix))
print(np.average(a_matrix))

9
1
5.0


In [14]:
# Option 2
print(a_matrix.max())
print(a_matrix.min())
print(a_matrix.mean())

9
1
5.0
