# Quick Example of Matrices in Action
- Create a matrix to represent a number
- Change the number from black to white
- Rotate the number

In [1]:
import numpy as np

## Create a matrix to represent a number

In [2]:
image_matrix = np.matrix([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]])
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [3]:
cross_matrix = np.matrix([[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]])
print(cross_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


## Change the number from black to white

In [4]:
rows = cross_matrix.shape[0]
columns = cross_matrix.shape[1]
print(rows, columns)

5 5


In [6]:
for row in range(rows):
    for column in range(columns):
        if cross_matrix[row, column] == 0:
            cross_matrix[row, column] = 1
        else:
            cross_matrix[row, column] = 0

print(cross_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [7]:
for row in range(rows):
    for column in range(columns):
        if image_matrix[row, column] == 0:
            image_matrix[row, column] = 1
        else:
            image_matrix[row, column] = 0

print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]]


## Rotate the number

In [8]:
print(image_matrix.T)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
print(image_matrix.flatten())

[[1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1]]
